import = [
  "~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
#TERM = "xterm-256color"
TERM = "alacritty"

[window]
padding.x = 10
padding.y = 5

decorations = "Buttonless"

opacity = 0.8
blur = true

option_as_alt = "Both"

[font]
size = 14

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "MesloLGS Nerd Font Mono"
style = "Bold Italic"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"
style = "Regular"

#[font]
#normal.family = "MesloLGS Nerd Font Mono"
#size = 14
