"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_green)\
$os\
$username\
[](bg:color_blue fg:color_green)\
$directory\
[](fg:color_blue bg:color_yellow)\
$git_branch\
$git_status\
[](fg:color_yellow bg:color_red)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_red bg:color_purple)\
$docker_context\
$conda\
[](fg:color_purple bg:color_white)\
$time\
[ ](fg:color_white)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
# rose-pine
color_fg0 = '#e0def4'
color_bg1 = '#191724' 
color_bg3 = '#575656'
color_blue = '#9ccfd8' 
color_aqua = '#ebbcba' 
color_green = '#31748f'
color_orange = '#d65d0e'
color_purple = '#c4a7e7'
color_red = '#eb6f92'
color_yellow = '#f6c177'
color_white = '#e0def4'
color_black = '#26233a'
color_bred = '#d16983'
color_byellow = '#ffeb95'

[os]
disabled = false
style = "bg:color_green fg:color_white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_green fg:color_white"
style_root = "bg:color_green fg:calor_white"
format = '[ $user ]($style)'

[directory]
style = "fg:color_bg1 bg:color_blue"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_bg1 bg:color_yellow)]($style)'

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_bg1 bg:color_yellow)]($style)'

[nodejs]
symbol = ""
style = "bg:color_purple"
format = '[[](fg:color_bg1 bg:color_red)]($style)'
#format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_red)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_red)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_bg1 bg:color_red)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_white"
format = '[[  $time ](fg:color_black bg:color_white)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
