"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](color_fg0)\
$os\
$username\
[](bg:color_bred fg:color_fg0)\
$directory\
[](fg:color_bred bg:color_green)\
$git_branch\
$git_status\
[](fg:color_green bg:color_aqua)\
$c\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color_aqua bg:color_purple)\
$docker_context\
$conda\
[](fg:color_purple bg:color_blue)\
$time\
[ ](fg:color_blue)\
$line_break$character"""

palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
# nightfox
color_fg0 = '#575860'
color_bg1 = '#9d79d6' 
color_bg3 = '#86abdc'
color_blue = '#719cd6' 
color_aqua = '#63cdcf' 
color_green = '#81b29a'
color_orange = '#d65d0e'
color_purple = '#9d79d6'
color_red = '#c94f6d' 
color_yellow = '#e0c989'
color_white = '#dfdfe0'
color_black = '#192330'
color_bred = '#d16983'

# catppuccin_macchiato
#color_fg0 = '#494D64' 
#color_bg1 = '#F5BDE6' 
#color_bg3 = '#8AADF4' 
#color_blue = '#8BD5CA' 
#color_aqua = '#A6DA95' 
#color_green = '#A6DA95' 
#color_orange = '#d65d0e'
#color_purple = '#b16286'
#color_red = '#ED8796' 
#color_yellow = '#EED49F' 
#color_white = '#B8C0E0'

[os]
disabled = false
style = "bg:color_fg0 fg:color_white"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "bg:color_fg0 fg:color_white"
style_root = "bg:color_fg0 fg:calor_white"
format = '[ $user ]($style)'

[directory]
style = "fg:color_white bg:color_bred"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_green"
format = '[[ $symbol $branch ](fg:color_white bg:color_green)]($style)'

[git_status]
style = "bg:color_green"
format = '[[($all_status$ahead_behind )](fg:color_white bg:color_green)]($style)'

[nodejs]
symbol = ""
style = "bg:color_purple"
format = '[[](fg:color_white bg:color_purple)]($style)'
#format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[c]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[rust]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[golang]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[php]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[java]
symbol = " "
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[kotlin]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[haskell]
symbol = ""
style = "bg:color_blue"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_blue)]($style)'

[python]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol( $version) ](fg:color_fg0 bg:color_aqua)]($style)'

[docker_context]
symbol = ""
style = "bg:color_bg3"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color_bg3)]($style)'

[conda]
style = "bg:color_bg3"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color_bg3)]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:color_blue"
format = '[[  $time ](fg:color_white bg:color_blue)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold fg:color_green)'
error_symbol = '[❯](bold fg:color_red)'
vimcmd_symbol = '[❮](bold fg:color_green)'
vimcmd_replace_one_symbol = '[❮](bold fg:color_purple)'
vimcmd_replace_symbol = '[❮](bold fg:color_purple)'
vimcmd_visual_symbol = '[❮](bold fg:color_yellow)'
