[manager]
show_hidden = true
show_symlink = true

[opener]
edit = [
  { run = 'nvim $@', block = true, desc = 'nvim', for = 'unix' }
]

# [plugin]
# prepend_previewers = [
#   { name = "*.*", exec = "bat" }
# ]
